spring:
  profiles:
    group:
      h2-basic: h2, basic
      h2-pst: h2, pst
      psql-basic:  psql, basic
      psql-pst: psql, pst
  jpa:
    show-sql: false
    format_sql: true
    generate-ddl: true
    ddl-auto: create-drop
    properties:
      hibernate:
        jdbc.batch_size: 5000
        order_inserts: true
        order_updates: true
        default_batch_fetch_size: 500
  datasource:
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
      idle-timeout: 30000
      connection-timeout: 30000
      max-lifetime: 1800000
crx:
  batch-size: 5000
  max-batch-iterations: 1000000
