CREATE OR REPLACE PROCEDURE finance_execution()
BEGIN
TRUNCATE TABLE TMP_INVOICE_CREDITOR;
TRUNCATE TABLE TMP_INVOICE_RATE;
TRUNCATE TABLE TMP_INVOICE_PURCHASER;

INSERT INTO TMP_INVOICE_CREDITOR (INVOICE_ID, CREDITOR_ID, FINANCING_TERM, MAX_FINANCING_RATE_IN_BPS)
SELECT INVOICE.ID,CREDITOR_ID,DATEDIFF('DAY', CURRENT_DATE, INVOICE.MATURITY_DATE), CREDITOR.MAX_FINANCING_RATE_IN_BPS FROM INVOICE
                                                                                                                                JOIN CREDITOR ON INVOICE.CREDITOR_ID = CREDITOR.ID
WHERE
        INVOICE.ID not in (select INVOICE_ID from FINANCING)
    limit 5;

INSERT INTO TMP_INVOICE_RATE (INVOICE_ID, PURCHASER_SETTINGS_ID, FINANCING_TERM, FINANCING_RATE)
SELECT INVOICE_ID, PURCHASER_FINANCING_SETTINGS.ID,FINANCING_TERM, FINANCING_TERM * PURCHASER_FINANCING_SETTINGS.ANNUAL_RATE_IN_BPS * 1.0/ 365  FROM TMP_INVOICE_CREDITOR
                                                                                                                                                         JOIN PURCHASER_FINANCING_SETTINGS ON TMP_INVOICE_CREDITOR.CREDITOR_ID = PURCHASER_FINANCING_SETTINGS.CREDITOR_ID
WHERE FINANCING_TERM * PURCHASER_FINANCING_SETTINGS.ANNUAL_RATE_IN_BPS * 1.0/365 < TMP_INVOICE_CREDITOR.MAX_FINANCING_RATE_IN_BPS;


INSERT INTO TMP_INVOICE_PURCHASER (INVOICE_ID, PURCHASER_ID,FINANCING_TERM,FINANCING_RATE,FINANCING_RATE_RANK)
SELECT INVOICE_ID, PURCHASER.ID, FINANCING_RATE, ROW_NUMBER() over(partition by INVOICE_ID
                               order by FINANCING_RATE) as FINANCING_RATE_RANK FROM TMP_INVOICE_RATE
                                                                                                                                                          JOIN PURCHASER_PURCHASER_FINANCING_SETTINGS ON TMP_INVOICE_RATE.PURCHASER_SETTINGS_ID = PURCHASER_PURCHASER_FINANCING_SETTINGS.PURCHASER_FINANCING_SETTINGS_ID
                                                                                                                                                          JOIN PURCHASER ON PURCHASER.ID = PURCHASER_PURCHASER_FINANCING_SETTINGS.PURCHASER_ID
WHERE FINANCING_TERM > PURCHASER.MINIMUM_FINANCING_TERM_IN_DAYS;

Insert into FINANCING (invoice_id, purchaser_id, date_fullfilment, term, rate, early_payment_amount)
SELECT invoice_id,purchaser_id,CURRENT_DATE,FINANCING_TERM,FINANCING_RATE,INVOICE.VALUE_IN_CENTS*(1-FINANCING_RATE/10000) FROM TMP_INVOICE_PURCHASER
                                                                                                                                   JOIN INVOICE ON INVOICE.ID = TMP_INVOICE_PURCHASER.invoice_id
WHERE FINANCING_RATE_RANK = 1
END;
